/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador;
import database.Conexao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.plaf.ColorUIResource;
import model.Usuario;
import view.Listeners.OuvidoConsultarUsuario;
import view.Listeners.OuvidoExcluirUsuario;

/**
 *
 * @author joseg github.com/JoseGabrielNF
 */
public class VerUsuarios extends javax.swing.JFrame {

    GridBagConstraints gbc = new GridBagConstraints();
    
    public VerUsuarios() {
        initComponents();
        Controlador.inicializarDados();
        this.setVisible(true);
        this.setTitle("Usuarios");
    }

    public void iniciaLabels(){
            tabela.setLayout(new GridBagLayout());
            gbc.anchor =  GridBagConstraints.CENTER; 
            gbc.fill= GridBagConstraints.CENTER;       
            gbc.weightx = 1.0  ;
            gbc.weighty = 1.0 ; 
            JLabel login=new JLabel("Login");
            JLabel email=new JLabel("Email");
            JLabel consultar=new JLabel("Consultar");
            JLabel excluir= new JLabel("Excluir");
            login.setPreferredSize(new Dimension(50, 50));
            email.setPreferredSize(new Dimension(50, 50));
            consultar.setPreferredSize(new Dimension(60, 50));
            excluir.setPreferredSize(new Dimension(50, 50));            
            gbc.gridx = 0;
            gbc.gridy = 0;
            tabela.add(login, gbc);
            gbc.gridx = 1;
            gbc.gridy = 0;
            tabela.add(email, gbc);
            gbc.gridx = 2;
            gbc.gridy = 0;
            tabela.add(consultar, gbc);
            gbc.gridx = 3;
            gbc.gridy = 0;
            tabela.add(excluir, gbc);
            
            gbc.anchor =  GridBagConstraints.LINE_START; 
            gbc.fill= GridBagConstraints.HORIZONTAL;     
    }
    public void preencher() {
        List<Usuario> usuarios = Controlador.lerUsuarios();
        int tamanhoTabela = 1;
        tabela.removeAll();
        repaint();
        iniciaLabels();

        for (int i = 0; i < usuarios.size(); i++) {
            JButton login = new JButton();
            JButton email = new JButton();
            JButton consultar = new JButton("Consultar");
            JButton excluir = new JButton("Excluir");

            login.setPreferredSize(new Dimension(100, 50));
            email.setPreferredSize(new Dimension(100, 50));
            consultar.setPreferredSize(new Dimension(100, 50));
            excluir.setPreferredSize(new Dimension(50, 50));    
           
            OuvidoConsultarUsuario consultarOuvido = new OuvidoConsultarUsuario();
            OuvidoExcluirUsuario excluirOuvido = new OuvidoExcluirUsuario();
            consultar.addActionListener(consultarOuvido);
            excluir.addActionListener(excluirOuvido);

            login.setText(usuarios.get(i).getLogin());
            email.setText(usuarios.get(i).getEmail());

            consultar.setName(usuarios.get(i).getId());
            excluir.setName(usuarios.get(i).getId());
                 
            gbc.gridx = 0;
            gbc.gridy = tamanhoTabela;
            tabela.add(login, gbc);
            gbc.gridx = 1;
            gbc.gridy = tamanhoTabela;
            tabela.add(email, gbc);
            gbc.gridx = 2;
            gbc.gridy = tamanhoTabela;
            tabela.add(consultar, gbc);
            gbc.gridx = 3;
            gbc.gridy = tamanhoTabela;
            tabela.add(excluir, gbc);

            tamanhoTabela++;
            repaint();
            revalidate();
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastrar = new javax.swing.JButton();
        painelRolagem = new javax.swing.JScrollPane();
        painelAuxiliar = new javax.swing.JPanel();
        tabela = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setType(java.awt.Window.Type.UTILITY);

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        painelRolagem.setBorder(null);

        javax.swing.GroupLayout tabelaLayout = new javax.swing.GroupLayout(tabela);
        tabela.setLayout(tabelaLayout);
        tabelaLayout.setHorizontalGroup(
            tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        tabelaLayout.setVerticalGroup(
            tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelAuxiliarLayout = new javax.swing.GroupLayout(painelAuxiliar);
        painelAuxiliar.setLayout(painelAuxiliarLayout);
        painelAuxiliarLayout.setHorizontalGroup(
            painelAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelAuxiliarLayout.setVerticalGroup(
            painelAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAuxiliarLayout.createSequentialGroup()
                .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 345, Short.MAX_VALUE))
        );

        painelRolagem.setViewportView(painelAuxiliar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelRolagem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        CadastrarUsuarios janela= new CadastrarUsuarios();
        janela.setVisible(true);
    }//GEN-LAST:event_CadastrarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        UIManager.put( "control", new Color( 128, 128, 128) );
        UIManager.put( "info", new Color(128,128,128) );
        UIManager.put( "nimbusBase", Color.BLACK);
        UIManager.put( "nimbusAlertYellow", new Color( 248, 187, 0) );
        UIManager.put( "nimbusDisabledText", new Color( 128, 128, 128) );
        UIManager.put( "nimbusFocus", new Color(115,164,209) );
        UIManager.put( "nimbusGreen", new Color(176,179,50) );
        UIManager.put( "nimbusInfoBlue", new Color( 66, 139, 221) );
        UIManager.put( "nimbusLightBackground", new Color(60,60,60) );
        UIManager.put( "nimbusOrange", new Color(191,98,4) );
        UIManager.put( "nimbusRed", new Color(169,46,34) );
        UIManager.put( "nimbusSelectedText", new Color( 255, 255, 255) );
        UIManager.put( "nimbusSelectionBackground", new Color( 104, 93, 156) );
        UIManager.put( "text", new Color( 230, 230, 230) );
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                 try {
                     Conexao.firebase();
                 } catch (IOException ex) {
                     Logger.getLogger(VerUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
                 VerUsuarios janela =new VerUsuarios();
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JPanel painelAuxiliar;
    private javax.swing.JScrollPane painelRolagem;
    private javax.swing.JPanel tabela;
    // End of variables declaration//GEN-END:variables
}
